- file:
    path: "{{ root_dir }}"
    state: directory

- file:
    path: "{{ systemd_dir }}"
    state: directory

- file:
    path: "{{ log_dir }}"
    state: directory

- file:
    path: "{{ env_dir }}"
    state: directory

- template:
    src: _env.env
    dest: "{{ root_dir }}/.env"

- template:
    src: systemd/_.service
    dest: "{{ systemd_dir }}/{{ service_name }}.service"

- file:
    src: "{{ systemd_dir }}/{{ service_name }}.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    state: link

- file:
    src: "{{ log_dir }}"
    dest: "/var/log/dynamodb"
    state: link
    
- debug:
    msg: "OK"
